version: "2.29"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend/uploads:/user/src/app/backend/uploads
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
      - REACT_APP_API_URL=http://188.225.87.151:3001
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://188.225.87.151:3001

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
